'use client';
import { useState } from 'react';
interface P { isOpen: boolean; onClose: () => void; onSubmit: (d: { title: string; description: string; category: string }) => Promise<void>; }
const CATS = [{ v: 'feature', l: 'Ominaisuus' }, { v: 'improvement', l: 'Parannus' }, { v: 'integration', l: 'Integraatio' }, { v: 'ui', l: 'Käyttöliittymä' }, { v: 'data', l: 'Data' }];
export default function NewItemModal({ isOpen, onClose, onSubmit }: P) {
  const [title, setTitle] = useState(''); const [desc, setDesc] = useState(''); const [cat, setCat] = useState('feature'); const [sub, setSub] = useState(false); const [err, setErr] = useState('');
  if (!isOpen) return null;
  const handle = async (e: React.FormEvent) => { e.preventDefault(); setErr(''); if (!title.trim() || !desc.trim()) { setErr('Täytä kaikki kentät'); return; } setSub(true); try { await onSubmit({ title: title.trim(), description: desc.trim(), category: cat }); setTitle(''); setDesc(''); setCat('feature'); onClose(); } catch { setErr('Ehdotuksen luonti epäonnistui'); } setSub(false); };
  return (<div className="fixed inset-0 z-50 flex items-center justify-center p-4"><div className="absolute inset-0 bg-black/60 backdrop-blur-sm" onClick={onClose} /><div className="relative w-full max-w-lg bg-zinc-900 border border-zinc-700 rounded-2xl shadow-2xl p-6"><div className="flex items-center justify-between mb-5"><h2 className="text-lg font-bold text-white">Ehdota uutta ominaisuutta</h2><button onClick={onClose} className="text-zinc-400 hover:text-white p-1"><svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" /></svg></button></div>{err && <div className="bg-red-900/30 border border-red-800/50 rounded-lg px-4 py-2 text-sm text-red-300 mb-4">{err}</div>}<form onSubmit={handle} className="space-y-4"><div><label htmlFor="title" className="block text-sm font-medium text-zinc-300 mb-1.5">Otsikko</label><input id="title" type="text" maxLength={100} required value={title} onChange={e => setTitle(e.target.value)} className="w-full bg-zinc-800 border border-zinc-700 rounded-lg px-4 py-2.5 text-white placeholder-zinc-500 focus:outline-none focus:ring-2 focus:ring-blue-500/50" placeholder="Esim. Reaaliaikainen bussiseuranta" /><span className="text-[11px] text-zinc-500 mt-1 block">{title.length}/100</span></div><div><label htmlFor="description" className="block text-sm font-medium text-zinc-300 mb-1.5">Kuvaus</label><textarea id="description" maxLength={500} required rows={4} value={desc} onChange={e => setDesc(e.target.value)} className="w-full bg-zinc-800 border border-zinc-700 rounded-lg px-4 py-2.5 text-white placeholder-zinc-500 focus:outline-none focus:ring-2 focus:ring-blue-500/50 resize-none" placeholder="Kuvaile ominaisuutta..." /><span className="text-[11px] text-zinc-500 mt-1 block">{desc.length}/500</span></div><div><label htmlFor="category" className="block text-sm font-medium text-zinc-300 mb-1.5">Kategoria</label><select id="category" value={cat} onChange={e => setCat(e.target.value)} className="w-full bg-zinc-800 border border-zinc-700 rounded-lg px-4 py-2.5 text-white focus:outline-none focus:ring-2 focus:ring-blue-500/50">{CATS.map(c => <option key={c.v} value={c.v}>{c.l}</option>)}</select></div><div className="flex gap-3 pt-2"><button type="button" onClick={onClose} className="flex-1 px-4 py-2.5 text-sm text-zinc-300 bg-zinc-800 hover:bg-zinc-700 border border-zinc-700 rounded-lg transition-colors">Peruuta</button><button type="submit" disabled={sub} className="flex-1 px-4 py-2.5 text-sm text-white bg-blue-600 hover:bg-blue-500 disabled:bg-blue-600/50 font-medium rounded-lg transition-colors">{sub ? 'Lähetetään...' : 'Lähetä ehdotus'}</button></div></form></div></div>);
}
