'use client';
import VoteButton from './VoteButton';
import StatusBadge from './StatusBadge';
import CategoryBadge from './CategoryBadge';
export interface RoadmapItem { id: string; title: string; description: string; category: string; status: string; author_id: string | null; is_official: boolean; vote_count: number; created_at: string; author_name?: string; }
interface P { item: RoadmapItem; hasVoted: boolean; onVoteToggle: (id: string) => void; isAdmin?: boolean; onEdit?: (item: RoadmapItem) => void; onDelete?: (id: string) => void; votingDisabled?: boolean; }
export default function RoadmapItemCard({ item, hasVoted, onVoteToggle, isAdmin, onEdit, onDelete, votingDisabled }: P) {
  return (<div className="bg-zinc-900/80 border border-zinc-800 rounded-xl p-4 flex gap-3"><VoteButton voteCount={item.vote_count} hasVoted={hasVoted} onToggle={() => onVoteToggle(item.id)} disabled={votingDisabled} /><div className="flex-1 min-w-0"><div className="flex items-start justify-between gap-2"><h3 className="text-sm font-semibold text-white leading-snug">{item.title}{item.is_official && <span className="ml-1.5 inline-flex items-center px-1.5 py-0.5 rounded text-[10px] font-medium bg-blue-600/20 text-blue-400 border border-blue-500/30">Virallinen</span>}</h3>{isAdmin && <div className="flex items-center gap-1 flex-shrink-0"><button onClick={() => onEdit?.(item)} className="p-1 text-zinc-500 hover:text-zinc-300" title="Muokkaa"><svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" /></svg></button><button onClick={() => onDelete?.(item.id)} className="p-1 text-zinc-500 hover:text-red-400" title="Poista"><svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" /></svg></button></div>}</div><p className="text-xs text-zinc-400 mt-1 line-clamp-2">{item.description}</p><div className="flex items-center gap-2 mt-2 flex-wrap"><StatusBadge status={item.status} /><CategoryBadge category={item.category} />{item.author_name && <span className="text-[11px] text-zinc-500">— {item.author_name}</span>}</div></div></div>);
}
